# Generated by Django 2.2.2 on 2019-06-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=25)),
                ('student_roll_no', models.IntegerField(max_length=5)),
                ('study_field', models.CharField(max_length=25)),
            ],
        ),
    ]
